/*
 * Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

import { dirname } from 'path-unified';
import chalk from 'chalk';
import { fs } from 'style-dictionary/fs';
import filterTokens from './filterTokens.js';
import GroupMessages from './utils/groupMessages.js';
import { composeMessage, inFile, logInfo, logWarning, mergeLogConfigs } from './logging/index.js';

import createFormatArgs from './utils/createFormatArgs.js';

/**
 * @typedef {import('../types/DesignToken.d.ts').Dictionary} Dictionary
 * @typedef {import('../types/DesignToken.d.ts').TransformedToken} TransformedToken
 * @typedef {import('../types/Config.d.ts').PlatformConfig} PlatformConfig
 * @typedef {import('../types/Config.d.ts').Config} Config
 * @typedef {import('../types/File.d.ts').File} File
 * @typedef {import('../types/Filter.d.ts').Matcher} Matcher
 * @typedef {import('../types/Format.d.ts').FormatterArguments} FormatterArguments
 */

/**
 * Takes the style token object and a format and returns a
 * string that can be written to a file.
 * @memberOf StyleDictionary
 * @param {File} file
 * @param {PlatformConfig} platform
 * @param {Dictionary} dictionary
 * @param {Config} options
 */
export default async function buildFile(file, platform = {}, dictionary, options) {
  const { destination } = file || {};
  const filter = /** @type {Matcher|undefined} */ (file.filter);
  const log = mergeLogConfigs(platform.log);
  let { format } = file || {};

  if (typeof format !== 'function') throw new Error('Please enter a valid file format');
  if (typeof destination !== 'string') throw new Error('Please enter a valid destination');

  // get if the format is nested, this needs to be done before
  // the function is bound
  const nested = format.nested;
  // to maintain backwards compatibility we bind the format to the file object
  format = format.bind(file);
  let fullDestination = destination;

  // if there is a build path, prepend the full destination with it
  if (platform.buildPath) {
    fullDestination = platform.buildPath + fullDestination;
  }

  const dir = dirname(fullDestination);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const filteredTokens = await filterTokens(dictionary, filter, options);
  const filteredDictionary = Object.assign({}, dictionary, {
    tokens: filteredTokens.tokens,
    allTokens: filteredTokens.allTokens,
    // keep the unfiltered tokens object for reference resolution
    unfilteredTokens: dictionary.tokens,
  });

  // if tokens object is empty, return without creating a file
  if (
    Object.hasOwn(filteredTokens, 'tokens') &&
    Object.keys(filteredTokens.tokens).length === 0 &&
    filteredTokens.tokens.constructor === Object
  ) {
    logInfo(chalk.rgb(255, 140, 0)(`No tokens for ${destination}. File not created.`), log);
    return null;
  }

  /**
   * Check for token name Collisions
   * @type {Record<string, TransformedToken[]>}
   */
  const nameCollisionObj = {};
  filteredTokens.allTokens &&
    filteredTokens.allTokens.forEach((tokenData) => {
      let tokenName = tokenData.name;
      if (!nameCollisionObj[tokenName]) {
        nameCollisionObj[tokenName] = [];
      }
      nameCollisionObj[tokenName].push(tokenData);
    });

  const PROPERTY_NAME_COLLISION_WARNINGS =
    GroupMessages.GROUP.PropertyNameCollisionWarnings + ':' + destination;
  GroupMessages.clear(PROPERTY_NAME_COLLISION_WARNINGS);
  Object.keys(nameCollisionObj).forEach((tokenName) => {
    if (nameCollisionObj[tokenName].length > 1) {
      let collisions = nameCollisionObj[tokenName]
        .map((token) => {
          let tokenPathText = chalk.rgb(255, 69, 0)(token.path.join('.'));
          let valueText = chalk.rgb(255, 140, 0)(options.usesDtcg ? token.$value : token.value);
          // the file a token was defined in makes collisions in large
          // dictionaries a lot easier to track down
          return `  ${tokenPathText}   ${valueText}${inFile(token.filePath)}`;
        })
        .join('\n');
      GroupMessages.add(
        PROPERTY_NAME_COLLISION_WARNINGS,
        `Output name ${chalk.rgb(255, 69, 0).bold(tokenName)} was generated by:\n${collisions}`,
      );
    }
  });

  const formattedContent = await format(
    createFormatArgs({
      dictionary: filteredDictionary,
      platform,
      options,
      file,
    }),
  );

  await fs.promises.writeFile(fullDestination, formattedContent);

  // don't show name collision warnings for nested type formats
  // because they are not relevant.
  const collisionWarnings = nested
    ? []
    : GroupMessages.fetchMessages(PROPERTY_NAME_COLLISION_WARNINGS);
  // always drain the group, or its messages leak into the next file we build
  const filteredReferencesWarnings = GroupMessages.flush(
    GroupMessages.GROUP.FilteredOutputReferences,
  );

  if (
    log.warnings === 'disabled' ||
    (collisionWarnings.length === 0 && filteredReferencesWarnings.length === 0)
  ) {
    logInfo(chalk.bold.green(`✔︎ ${fullDestination}`), log);
    return;
  }

  const warnHeader = `⚠️ ${fullDestination}`;

  if (collisionWarnings.length > 0) {
    const summary = `${warnHeader}\nWhile building ${chalk
      .rgb(255, 69, 0)
      .bold(destination)}, token collisions were found (${
      collisionWarnings.length
    }); output may be unexpected.`;
    const help = chalk.rgb(
      255,
      165,
      0,
    )(
      [
        'This many-to-one issue is usually caused by some combination of:',
        '* conflicting or similar paths/names in token definitions',
        '* platform transforms/transformGroups affecting names, especially when removing specificity',
        '* overly inclusive file filters',
      ].join('\n'),
    );
    logWarning(`${composeMessage(summary, collisionWarnings, log)}\n${help}`, log);
  }

  if (filteredReferencesWarnings.length > 0) {
    const summary = `${warnHeader}\nWhile building ${chalk
      .rgb(255, 69, 0)
      .bold(destination)}, filtered out token references were found (${
      filteredReferencesWarnings.length
    }); output may be unexpected.`;
    const help = chalk.rgb(
      255,
      165,
      0,
    )('This is caused when combining a filter and `outputReferences`.');
    const details = filteredReferencesWarnings.map((ref) => `  ${ref}`);
    logWarning(`${composeMessage(summary, details, log)}\n${help}`, log);
  }
}
