/*
 * Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
 * the License. A copy of the License is located at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions
 * and limitations under the License.
 */

import { dirname } from 'path-unified';
import chalk from 'chalk';
import { fs } from 'style-dictionary/fs';
import filterTokens from './filterTokens.js';
import GroupMessages from './utils/groupMessages.js';
import { isVerbose, log } from './utils/logger.js';

import createFormatArgs from './utils/createFormatArgs.js';

/**
 * @typedef {import('../types/DesignToken.d.ts').Dictionary} Dictionary
 * @typedef {import('../types/DesignToken.d.ts').TransformedToken} TransformedToken
 * @typedef {import('../types/Config.d.ts').PlatformConfig} PlatformConfig
 * @typedef {import('../types/Config.d.ts').Config} Config
 * @typedef {import('../types/File.d.ts').File} File
 * @typedef {import('../types/Filter.d.ts').Matcher} Matcher
 * @typedef {import('../types/Format.d.ts').FormatterArguments} FormatterArguments
 */

/**
 * Takes the style token object and a format and returns a
 * string that can be written to a file.
 * @memberOf StyleDictionary
 * @param {File} file
 * @param {PlatformConfig} platform
 * @param {Dictionary} dictionary
 * @param {Config} options
 */
export default async function buildFile(file, platform = {}, dictionary, options) {
  const { destination } = file || {};
  const filter = /** @type {Matcher|undefined} */ (file.filter);
  let { format } = file || {};

  if (typeof format !== 'function') throw new Error('Please enter a valid file format');
  if (typeof destination !== 'string') throw new Error('Please enter a valid destination');

  // get if the format is nested, this needs to be done before
  // the function is bound
  const nested = format.nested;
  // to maintain backwards compatibility we bind the format to the file object
  format = format.bind(file);
  let fullDestination = destination;

  // if there is a build path, prepend the full destination with it
  if (platform.buildPath) {
    fullDestination = platform.buildPath + fullDestination;
  }

  const dir = dirname(fullDestination);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const filteredTokens = await filterTokens(dictionary, filter, options);
  const filteredDictionary = Object.assign({}, dictionary, {
    tokens: filteredTokens.tokens,
    allTokens: filteredTokens.allTokens,
    // keep the unfiltered tokens object for reference resolution
    unfilteredTokens: dictionary.tokens,
  });

  // if tokens object is empty, return without creating a file
  if (
    Object.hasOwn(filteredTokens, 'tokens') &&
    Object.keys(filteredTokens.tokens).length === 0 &&
    filteredTokens.tokens.constructor === Object
  ) {
    log(chalk.rgb(255, 140, 0)(`No tokens for ${destination}. File not created.`));
    return null;
  }

  /**
   * Check for token name Collisions
   * @type {Record<string, TransformedToken[]>}
   */
  const nameCollisionObj = {};
  filteredTokens.allTokens &&
    filteredTokens.allTokens.forEach((tokenData) => {
      let tokenName = tokenData.name;
      if (!nameCollisionObj[tokenName]) {
        nameCollisionObj[tokenName] = [];
      }
      nameCollisionObj[tokenName].push(tokenData);
    });

  const PROPERTY_NAME_COLLISION_WARNINGS =
    GroupMessages.GROUP.PropertyNameCollisionWarnings + ':' + destination;
  GroupMessages.clear(PROPERTY_NAME_COLLISION_WARNINGS);
  Object.keys(nameCollisionObj).forEach((tokenName) => {
    if (nameCollisionObj[tokenName].length > 1) {
      let collisions = nameCollisionObj[tokenName]
        .map((token) => {
          let tokenPathText = chalk.rgb(255, 69, 0)(token.path.join('.'));
          let valueText = chalk.rgb(255, 140, 0)(options.usesDtcg ? token.$value : token.value);
          return tokenPathText + '   ' + valueText;
        })
        .join('\n        ');
      GroupMessages.add(
        PROPERTY_NAME_COLLISION_WARNINGS,
        `Output name ${chalk
          .rgb(255, 69, 0)
          .bold(tokenName)} was generated by:\n        ${collisions}`,
      );
    }
  });

  const tokenNamesCollisionCount = GroupMessages.count(PROPERTY_NAME_COLLISION_WARNINGS);

  const formattedContent = await format(
    createFormatArgs({
      dictionary: filteredDictionary,
      platform,
      options,
      file,
    }),
  );

  const filteredReferencesCount = GroupMessages.count(GroupMessages.GROUP.FilteredOutputReferences);
  // flush once, so the messages don't leak into the next file that is built
  const filteredReferencesWarnings = GroupMessages.flush(
    GroupMessages.GROUP.FilteredOutputReferences,
  );

  // don't show name collision warnings for nested type formats
  // because they are not relevant.
  const hasNameCollisions = !nested && tokenNamesCollisionCount > 0;
  const hasFilteredReferences = filteredReferencesCount > 0;

  const warnHeader = `⚠️ ${fullDestination}`;

  /**
   * Full collision warning, only shown in verbose mode.
   * @returns {string}
   */
  const nameCollisionWarning = () => {
    const tokenNamesCollisionWarnings = GroupMessages.fetchMessages(
      PROPERTY_NAME_COLLISION_WARNINGS,
    ).join('\n    ');
    const title = `While building ${chalk
      .rgb(255, 69, 0)
      .bold(destination)}, token collisions were found; output may be unexpected.`;
    const help = chalk.rgb(
      255,
      165,
      0,
    )(
      [
        'This many-to-one issue is usually caused by some combination of:',
        '* conflicting or similar paths/names in token definitions',
        '* platform transforms/transformGroups affecting names, especially when removing specificity',
        '* overly inclusive file filters',
      ].join('\n    '),
    );
    return `${warnHeader}\n${title}\n    ${tokenNamesCollisionWarnings}\n${help}`;
  };

  /**
   * Concise collision message shown by default, so a build with many
   * collisions doesn't flood the console.
   * @returns {string}
   */
  const nameCollisionSummary = () =>
    `${warnHeader}\nWhile building ${chalk
      .rgb(255, 69, 0)
      .bold(
        destination,
      )}, token collisions were found; output may be unexpected.\n    ${tokenNamesCollisionCount} token collision${
      tokenNamesCollisionCount === 1 ? '' : 's'
    } found. Run with --verbose to see the details.`;

  /**
   * @returns {string}
   */
  const filteredReferencesWarning = () =>
    `${warnHeader}\nWhile building ${chalk
      .rgb(255, 69, 0)
      .bold(
        destination,
      )}, filtered out token references were found; output may be unexpected. Here are the references that are used but not defined in the file\n    ${filteredReferencesWarnings.join(
      '\n    ',
    )}\n${chalk.rgb(
      255,
      165,
      0,
    )('This is caused when combining a filter and `outputReferences`.')}`;

  /**
   * Concise filtered references message shown by default.
   * @returns {string}
   */
  const filteredReferencesSummary = () =>
    `${warnHeader}\nWhile building ${chalk
      .rgb(255, 69, 0)
      .bold(
        destination,
      )}, filtered out token references were found; output may be unexpected.\n    ${filteredReferencesCount} filtered out reference${
      filteredReferencesCount === 1 ? '' : 's'
    } found. Run with --verbose to see the details.\n${chalk.rgb(
      255,
      165,
      0,
    )('This is caused when combining a filter and `outputReferences`.')}`;

  // In error mode, collisions and filtered out references abort the build
  // before the file is written, rather than being logged as warnings.
  if (platform?.log === 'error') {
    if (hasNameCollisions) {
      throw new Error(nameCollisionWarning());
    }
    if (hasFilteredReferences) {
      throw new Error(filteredReferencesWarning());
    }
  }

  await fs.promises.writeFile(fullDestination, formattedContent);

  if (!hasNameCollisions && !hasFilteredReferences) {
    log(chalk.bold.green(`✔︎ ${fullDestination}`));
    return;
  }

  if (hasNameCollisions) {
    log(chalk.rgb(255, 140, 0).bold(isVerbose() ? nameCollisionWarning() : nameCollisionSummary()));
  }

  if (hasFilteredReferences) {
    log(
      chalk
        .rgb(255, 140, 0)
        .bold(isVerbose() ? filteredReferencesWarning() : filteredReferencesSummary()),
    );
  }
}
