/* @web/test-runner snapshot v1 */
export const snapshots = {};
snapshots["integration logging file should warn user empty tokens"] = 
`
css
No tokens for empty.css. File not created.`;
/* end snapshot integration logging file should warn user empty tokens */

snapshots["integration logging file should warn user of name collisions"] = 
`
css
⚠️ __integration__/build/nameCollisions.css
While building nameCollisions.css, token collisions were found (19); output may be unexpected.
Use log.verbosity "verbose" or CLI option --verbose for more details.
This many-to-one issue is usually caused by some combination of:
* conflicting or similar paths/names in token definitions
* platform transforms/transformGroups affecting names, especially when removing specificity
* overly inclusive file filters`;
/* end snapshot integration logging file should warn user of name collisions */

snapshots["integration logging file should warn user of filtered references"] = 
`
css
⚠️ __integration__/build/filteredReferences.css
While building filteredReferences.css, filtered out token references were found (7); output may be unexpected.
Use log.verbosity "verbose" or CLI option --verbose for more details.
This is caused when combining a filter and \`outputReferences\`.`;
/* end snapshot integration logging file should warn user of filtered references */

snapshots["integration logging file should not warn user of name collisions with warnings set to error"] = 
`⚠️ __integration__/build/nameCollisions.css
While building nameCollisions.css, token collisions were found (19); output may be unexpected.
Use log.verbosity "verbose" or CLI option --verbose for more details.
This many-to-one issue is usually caused by some combination of:
* conflicting or similar paths/names in token definitions
* platform transforms/transformGroups affecting names, especially when removing specificity
* overly inclusive file filters`;
/* end snapshot integration logging file should not warn user of name collisions with warnings set to error */

snapshots["integration logging file should list every filtered out reference when verbose"] = 
`
css
⚠️ __integration__/build/filteredReferences.css
While building filteredReferences.css, filtered out token references were found (7); output may be unexpected.

color.core.neutral.100
color.core.neutral.0
color.core.neutral.200
color.core.red.0
color.core.orange.0
color.core.green.0
color.core.blue.0
This is caused when combining a filter and \`outputReferences\`.`;
/* end snapshot integration logging file should list every filtered out reference when verbose */

snapshots["integration logging file should not warn user of filtered references with warnings set to error"] = 
`⚠️ __integration__/build/filteredReferences.css
While building filteredReferences.css, filtered out token references were found (7); output may be unexpected.
Use log.verbosity "verbose" or CLI option --verbose for more details.
This is caused when combining a filter and \`outputReferences\`.`;
/* end snapshot integration logging file should not warn user of filtered references with warnings set to error */

snapshots["integration logging file should list every name collision and the file it came from when verbose"] = 
`
css
⚠️ __integration__/build/nameCollisions.css
While building nameCollisions.css, token collisions were found (2); output may be unexpected.

Output name 0 was generated by:
color.core.green.0   #ebf9eb (__integration__/tokens/color/core.json)
color.core.neutral.0   #FFFFFF (__integration__/tokens/color/core.json)
Output name 100 was generated by:
color.core.green.100   #d7f4d7 (__integration__/tokens/color/core.json)
color.core.neutral.100   #f3f4f4 (__integration__/tokens/color/core.json)
This many-to-one issue is usually caused by some combination of:
* conflicting or similar paths/names in token definitions
* platform transforms/transformGroups affecting names, especially when removing specificity
* overly inclusive file filters`;
/* end snapshot integration logging file should list every name collision and the file it came from when verbose */

