/* @web/test-runner snapshot v1 */
export const snapshots = {};
snapshots["integration logging file should warn user empty tokens"] = 
`
css
No tokens for empty.css. File not created.`;
/* end snapshot integration logging file should warn user empty tokens */

snapshots["integration logging file should warn user of name collisions"] = 
`
css
⚠️ __integration__/build/nameCollisions.css
While building nameCollisions.css, token collisions were found; output may be unexpected.
Output name 0 was generated by:
color.core.green.0   #ebf9eb
color.core.teal.0   #e5f9f5
color.core.aqua.0   #d9fcfb
color.core.blue.0   #e9f8ff
color.core.purple.0   #f2f2f9
color.core.magenta.0   #fef0ff
color.core.pink.0   #ffe9f3
color.core.red.0   #ffeae9
color.core.orange.0   #ffede3
color.core.neutral.0   #FFFFFF
color.core.yellow.0   #fff8e2
Output name 100 was generated by:
color.core.green.100   #d7f4d7
color.core.teal.100   #cdf7ef
color.core.aqua.100   #c5f9f9
color.core.blue.100   #dcf2ff
color.core.purple.100   #eaeaf9
color.core.magenta.100   #f9e3fc
color.core.pink.100   #fcdbeb
color.core.red.100   #ffd5d2
color.core.orange.100   #fcdccc
color.core.neutral.100   #f3f4f4
color.core.yellow.100   #fdefcd
Output name 200 was generated by:
color.core.green.200   #c2f2bd
color.core.teal.200   #b3f2e6
color.core.aqua.200   #a5f2f2
color.core.blue.200   #c7e4f9
color.core.purple.200   #d8d7f9
color.core.magenta.200   #f4c4f7
color.core.pink.200   #ffb5d5
color.core.red.200   #ffb8b1
color.core.orange.200   #ffc6a4
color.core.neutral.200   #dee1e1
color.core.yellow.200   #ffe99a
Output name 300 was generated by:
color.core.green.300   #98e58e
color.core.teal.300   #7dead5
color.core.aqua.300   #76e5e2
color.core.blue.300   #a1d2f8
color.core.purple.300   #c1c1f7
color.core.magenta.300   #edadf2
color.core.pink.300   #ff95c1
color.core.red.300   #ff9c8f
color.core.orange.300   #ffb180
color.core.neutral.300   #c8cccc
color.core.yellow.300   #ffe16e
Output name 400 was generated by:
color.core.green.400   #75dd66
color.core.teal.400   #24e0c5
color.core.aqua.400   #33d6e2
color.core.blue.400   #56adf5
color.core.purple.400   #a193f2
color.core.magenta.400   #f282f5
color.core.pink.400   #ff76ae
color.core.red.400   #ff7f6e
color.core.orange.400   #ff9c5d
color.core.neutral.400   #b0b6b7
color.core.yellow.400   #ffd943
...and 14 more (19 total). Run with --verbose to see all of them.
This many-to-one issue is usually caused by some combination of:
* conflicting or similar paths/names in token definitions
* platform transforms/transformGroups affecting names, especially when removing specificity
* overly inclusive file filters`;
/* end snapshot integration logging file should warn user of name collisions */

snapshots["integration logging file should not warn user of name collisions with log level set to error"] = 
`⚠️ __integration__/build/nameCollisions.css
While building nameCollisions.css, token collisions were found; output may be unexpected.
Output name 0 was generated by:
color.core.green.0   #ebf9eb
color.core.teal.0   #e5f9f5
color.core.aqua.0   #d9fcfb
color.core.blue.0   #e9f8ff
color.core.purple.0   #f2f2f9
color.core.magenta.0   #fef0ff
color.core.pink.0   #ffe9f3
color.core.red.0   #ffeae9
color.core.orange.0   #ffede3
color.core.neutral.0   #FFFFFF
color.core.yellow.0   #fff8e2
Output name 100 was generated by:
color.core.green.100   #d7f4d7
color.core.teal.100   #cdf7ef
color.core.aqua.100   #c5f9f9
color.core.blue.100   #dcf2ff
color.core.purple.100   #eaeaf9
color.core.magenta.100   #f9e3fc
color.core.pink.100   #fcdbeb
color.core.red.100   #ffd5d2
color.core.orange.100   #fcdccc
color.core.neutral.100   #f3f4f4
color.core.yellow.100   #fdefcd
Output name 200 was generated by:
color.core.green.200   #c2f2bd
color.core.teal.200   #b3f2e6
color.core.aqua.200   #a5f2f2
color.core.blue.200   #c7e4f9
color.core.purple.200   #d8d7f9
color.core.magenta.200   #f4c4f7
color.core.pink.200   #ffb5d5
color.core.red.200   #ffb8b1
color.core.orange.200   #ffc6a4
color.core.neutral.200   #dee1e1
color.core.yellow.200   #ffe99a
Output name 300 was generated by:
color.core.green.300   #98e58e
color.core.teal.300   #7dead5
color.core.aqua.300   #76e5e2
color.core.blue.300   #a1d2f8
color.core.purple.300   #c1c1f7
color.core.magenta.300   #edadf2
color.core.pink.300   #ff95c1
color.core.red.300   #ff9c8f
color.core.orange.300   #ffb180
color.core.neutral.300   #c8cccc
color.core.yellow.300   #ffe16e
Output name 400 was generated by:
color.core.green.400   #75dd66
color.core.teal.400   #24e0c5
color.core.aqua.400   #33d6e2
color.core.blue.400   #56adf5
color.core.purple.400   #a193f2
color.core.magenta.400   #f282f5
color.core.pink.400   #ff76ae
color.core.red.400   #ff7f6e
color.core.orange.400   #ff9c5d
color.core.neutral.400   #b0b6b7
color.core.yellow.400   #ffd943
...and 14 more (19 total). Run with --verbose to see all of them.
This many-to-one issue is usually caused by some combination of:
* conflicting or similar paths/names in token definitions
* platform transforms/transformGroups affecting names, especially when removing specificity
* overly inclusive file filters`;
/* end snapshot integration logging file should not warn user of name collisions with log level set to error */

snapshots["integration logging file should warn user of filtered references"] =
`
css
⚠️ __integration__/build/filteredReferences.css
While building filteredReferences.css, filtered out token references were found; output may be unexpected. Here are the references that are used but not defined in the file
color.core.neutral.100
color.core.neutral.0
color.core.neutral.200
color.core.red.0
color.core.orange.0
color.core.green.0
color.core.blue.0
This is caused when combining a filter and \`outputReferences\`.`;
/* end snapshot integration logging file should warn user of filtered references */

snapshots["integration logging file should not warn user of filtered references with log level set to error"] = 
`⚠️ __integration__/build/filteredReferences.css
While building filteredReferences.css, filtered out token references were found; output may be unexpected. Here are the references that are used but not defined in the file
color.core.neutral.100
color.core.neutral.0
color.core.neutral.200
color.core.red.0
color.core.orange.0
color.core.green.0
color.core.blue.0
This is caused when combining a filter and \`outputReferences\`.`;
/* end snapshot integration logging file should not warn user of filtered references with log level set to error */

